.code_quality:
  stage: test
  image: "cirrusci/flutter:stable"
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  image: cirrusci/flutter:stable
  before_script:
    - cd frontend 
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs
  script:
    - flutter test -r expanded --machine --coverage | tojunit -o report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
    - flutter test -r expanded
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - report.xml
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml

.deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
