
frontend:
  trigger:
    include:
       - local: frontend/.frontend_gitlab_ci.yml
    strategy: depend

api_backend:
  trigger:
    include:
       - local: backend/Api_Backend/.api_backend_gitlab_ci.yml
    strategy: depend

load_balancer:
  trigger:
    include:
       - local: backend/Load_Balancer/.load_balancer_gitlab_ci.yml
    strategy: depend

.deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
