test:
  stage: test
  image: maven:3.8.7-amazoncorretto-19
  before_script:
    - cd backend/Load_Balancer 
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - mvn clean install
  script:
    - mvn verify 
  artifacts:
    paths:
      - $CI_PROJECT_DIR
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/TEST-*.xml
