load-test:
  stage: test
  image: maven:3.8.7-amazoncorretto-19
  before_script:
    - cd backend/Load_Balancer 
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - mvn clean install
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - mvn verify 
  artifacts:
    paths:
      - $CI_PROJECT_DIR/backend/Load_Balancer/target/site/jacoco/jacoco.xml
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/backend/Load_Balancer/target/surefire-reports/TEST-*.xml


load-coverage:
  stage: deploy
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py $CI_PROJECT_DIR/backend/Load_Balancer/target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/backend/Load_Balancer/src/main/java/ > $CI_PROJECT_DIR/backend/Load_Balancer/target/site/cobertura.xml
  needs: ["load-test"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $CI_PROJECT_DIR/backend/Load_Balancer/target/site/cobertura.xml
