backend-test:
  stage: test
  image: maven:3.8.7-amazoncorretto-19
  before_script:
    - cd backend/Api_Backend 
    - export PATH="$PATH:$HOME/.pub-cache/bin"
    - mvn clean install
  script:
    - mvn verify 
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
      - $CI_PROJECT_DIR
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/TEST-*.xml


backend-coverage:
  stage: deploy
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["backend-test"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml

