// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc8id5P7Ragb9RTYdc56dV3JC3R6gA0tQ',
    appId: '1:544381886081:web:16e1d7212009fd88bf7780',
    messagingSenderId: '544381886081',
    projectId: 'group-9-c4e02',
    authDomain: 'group-9-c4e02.firebaseapp.com',
    databaseURL: 'https://group-9-c4e02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'group-9-c4e02.appspot.com',
    measurementId: 'G-S534BYTCDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFnGMcCorMRE78y2jldgXRQ4b_mBTWFo',
    appId: '1:544381886081:android:50743466f47085a7bf7780',
    messagingSenderId: '544381886081',
    projectId: 'group-9-c4e02',
    databaseURL: 'https://group-9-c4e02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'group-9-c4e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77bFSRhinPMqSjIblGMCZpPRDHUGRuWU',
    appId: '1:544381886081:ios:b07aa2029a99f71dbf7780',
    messagingSenderId: '544381886081',
    projectId: 'group-9-c4e02',
    databaseURL: 'https://group-9-c4e02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'group-9-c4e02.appspot.com',
    iosClientId: '544381886081-hg48gaotuqa3vh6kk6b6cvd8nc722r3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC77bFSRhinPMqSjIblGMCZpPRDHUGRuWU',
    appId: '1:544381886081:ios:b07aa2029a99f71dbf7780',
    messagingSenderId: '544381886081',
    projectId: 'group-9-c4e02',
    databaseURL: 'https://group-9-c4e02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'group-9-c4e02.appspot.com',
    iosClientId: '544381886081-hg48gaotuqa3vh6kk6b6cvd8nc722r3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );
}
